USE [master]
GO

/****** Object:  Database [RieltorDip]    Script Date: 23.06.2023 10:52:10 ******/
CREATE DATABASE [RieltorDip]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RieltorDip', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RieltorDip.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RieltorDip_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RieltorDip_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RieltorDip].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RieltorDip] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RieltorDip] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RieltorDip] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RieltorDip] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RieltorDip] SET ARITHABORT OFF 
GO

ALTER DATABASE [RieltorDip] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RieltorDip] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RieltorDip] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RieltorDip] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RieltorDip] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RieltorDip] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RieltorDip] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RieltorDip] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RieltorDip] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RieltorDip] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RieltorDip] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RieltorDip] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RieltorDip] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RieltorDip] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RieltorDip] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RieltorDip] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RieltorDip] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RieltorDip] SET RECOVERY FULL 
GO

ALTER DATABASE [RieltorDip] SET  MULTI_USER 
GO

ALTER DATABASE [RieltorDip] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RieltorDip] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RieltorDip] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RieltorDip] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RieltorDip] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RieltorDip] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RieltorDip] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RieltorDip] SET  READ_WRITE 
GO

