//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltorAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartament()
        {
            this.Deal = new HashSet<Deal>();
            this.Image = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public int Id_City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public Nullable<int> Flat { get; set; }
        public int Area { get; set; }
        public int Rooms { get; set; }
        public Nullable<int> Floor { get; set; }
        public int Id_Type { get; set; }
        public int Price { get; set; }
        public bool Repair { get; set; }
        public int Id_Type_Of_Rooms { get; set; }
        public double High_Of_Roof { get; set; }
        public int Id_Type_Of_Toilet { get; set; }
        public int Floor_In_House { get; set; }
        public bool Lift { get; set; }
        public int Id_Type_Of_Parking { get; set; }
        public int Id_Client { get; set; }
        public int Id_Rieltor { get; set; }
        public int Id_Type_Of_Operation { get; set; }
        public bool Sold { get; set; }
        public Nullable<int> Id_Metro { get; set; }
        public Nullable<int> Id_District { get; set; }
        public string Image1 { get; set; }
    
        public virtual City City { get; set; }
        public virtual Client Client { get; set; }
        public virtual Type_Of_House Type_Of_House { get; set; }
        public virtual Type_Of_Operation Type_Of_Operation { get; set; }
        public virtual Type_Of_Parking Type_Of_Parking { get; set; }
        public virtual Type_Of_Rooms Type_Of_Rooms { get; set; }
        public virtual Type_Of_Toilet Type_Of_Toilet { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Image { get; set; }
        public virtual Districts Districts { get; set; }
        public virtual Metro Metro { get; set; }
    }
}
