//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltorAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Id { get; set; }
        public int Id_Demand { get; set; }
        public int Id_Apartament { get; set; }
    
        public virtual Apartament Apartament { get; set; }
        public virtual Demands Demands { get; set; }
    }
}
