//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltorAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demands()
        {
            this.Deal = new HashSet<Deal>();
        }
    
        public int Id { get; set; }
        public int Id_City { get; set; }
        public Nullable<int> MinPrise { get; set; }
        public Nullable<int> MaxPrise { get; set; }
        public Nullable<int> Id_Rieltor { get; set; }
        public int Id_Client { get; set; }
        public int Id_Type_Of_Operation { get; set; }
        public Nullable<int> MinArea { get; set; }
        public Nullable<int> MaxArea { get; set; }
        public Nullable<int> MinRooms { get; set; }
        public Nullable<int> MaxRooms { get; set; }
        public Nullable<int> MinFloor { get; set; }
        public Nullable<int> MaxFloor { get; set; }
        public int Id_Type_Of_House { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
        public virtual Type_Of_House Type_Of_House { get; set; }
        public virtual Type_Of_Operation Type_Of_Operation { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual City City { get; set; }
    }
}
