//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltorAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RieltorDipEntities : DbContext
    {
        public RieltorDipEntities()
            : base("name=RieltorDipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartament> Apartament { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Deal> Deal { get; set; }
        public virtual DbSet<Demands> Demands { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Metro> Metro { get; set; }
        public virtual DbSet<Type_Of_House> Type_Of_House { get; set; }
        public virtual DbSet<Type_Of_Operation> Type_Of_Operation { get; set; }
        public virtual DbSet<Type_Of_Parking> Type_Of_Parking { get; set; }
        public virtual DbSet<Type_Of_Rooms> Type_Of_Rooms { get; set; }
        public virtual DbSet<Type_Of_Toilet> Type_Of_Toilet { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
